
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import NavbarPage from "./component/Navbar";
import Mosquee from "./component/mosquee";

const notoSerifbengali = Noto_Serif_Bengali({
  variable: "--font-geist-sans",
  subsets: ["latin", "bengali"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSerifbengali.variable}  h-full antialiased`}
    >
      <body className="bg-[#f8faf8] min-h-full flex flex-col ">
        <NavbarPage></NavbarPage>
        <Mosquee></Mosquee>
        <div className="mx-auto w-full max-w-[1100px]">
          {children}
        </div>
      </body>
    </html>
  );
}
